### ISSUE TITLE
출시를 위한 메인뷰 수정

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#104]
## 🛠 Issue
- 가독성&자꾸 뜨는 오류 해결... 을 위한 메인뷰 코드 리팩토링
- 다크모드 버튼 텍스트가 안보이는 것 수정 
- 아티스트 이미지 없을 때 보이는 사진 수정

## 📝 To-do
- [x] mainView 보기 편하게 만들기
- [x] 다크모드 버튼 안보이는 오류 수정 
- [x]  아티스트 이미지 없을 때 보이는 사진 수정
