### ISSUE TITLE
디자인 디테일 수정 및 버그수정

### ISSUE THREAD

**Issue by Oreo-Mcflurry** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#105]
## 🛠 Issue
- 디자인 디테일 수정 및 버그수정

## 📝 To-do
- [x] Navigation Title -> Toolbar로 바꾸기
- [x] 아카이빙뷰 멀티선택 제거
- [x] 아카이빙뷰에서 세트리스트 넘어갈때 버벅임 제거
- [x] 세트리스트 삭제시 필터 삭제 안되는 버그 해결
