### ISSUE TITLE
QA이슈 해결

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#144]
## 🐛 Description
QA이슈 잡(으려고 노력해보)기
- 서치뷰에서 스크롤 안 되는 문제 
- 서치바 아래 검정 부분 문제
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/9da308b9-08c8-4ff9-ae1d-07003ff3ff0e)
- ProgressView 배경 문제
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/b8b233f4-5d13-4d7a-af35-4d8ac0dee771)
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/48026be1-c873-4de9-8db7-ebf08592e70f)
- ArtistView에서 하트를 계속 누르면 안 눌리고 멈추는 문제
## 📝 TODO
- [x] 서치뷰에서 스크롤 안 되는 문제 해결
- [x] 서치바 아래 검정 부분 해결
- [x] ProgressView 배경 문제 해결
- [x] ArtistView에서 하트를 계속 누르면 안 눌리고 멈추는 문제 해결
