### ISSUE TITLE
뷰 변경사항 적용

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#148]
## 🛠 Issue
- 여러 뷰들의 변경사항을 적용합니다.

## 📝 To-do
- [x] SearchView 하단 패딩
- [x] ArtistView 패딩
- [x] ArchivingView 전체 태그 추가
- [x] ArchivingView 패딩
- [x] SplashView 2초 나오게 하기
- [x] OnboardingView 수정
- [ ] TabBar 수정
