### ISSUE TITLE
세트리스트 캡처하기 수정

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#152]
## 🐛 Description
1. 커버곡에도 메인 아티스트 이름이 들어가는 문제 발생
2. 한글화 안 된 세트리스트가 내보내짐
3. 영어 제목이 먼저 들어간 뒤 한글 제목이 또 들어감. 원래 제목이 영어인 것은 한글 제목이 추가될 때는 제외됨

## 📝 TODO
- [x] 배열을 [(songTitle, artistName)] 형태로 전달
- [x] 내보내기용 배열을 만드는 시점을 '플레이리스트 내보내기' 버튼을 눌렀을 때로 수정
- [x] createArrayForExportPlaylist 함수 호출될 때 기존 배열 초기화
