### ISSUE TITLE
디테일 수정

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#157]
## 🛠 Issue
- 짜잘한 디테일을 수정합니다

## 📝 To-do
- [x] 애플뮤직 내보내기 버튼에서 최초 권한 허용 창 뜰 때 제목 설정 창 같이 뜸
- [x] 세트리스트 캡처 버튼에서 최초 권한 허용 창 뜰 때 토스트메시지 같이 뜸(실제로 사진 추가는 안 되는 상태)
- [x] customAlert 안에서 수행할 함수 viewModel로 옮기기
- [x] 메인뷰 닉네임 패딩 수정
- [x] 메인뷰 세트리스트 3개 미만일 떄 화면 내려가는 문제 수정
