### ISSUE TITLE
공유하기 뷰 만들기

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#160]
## 🛠 Issue
- 공유하기 뷰를 만듭니다.

## 📝 To-do
- [ ] 아티스트, 투어이름, 공연장소, 공연날짜 받아오기
- [ ] 새로운 공연날짜 포멧 만들기(Nov 20, 2023)
- [ ] 곡의 갯수에 맞게 뷰 그리기
- [ ] 티켓 배경 만들기
- [ ] 할 수 있겠지?

**Comment by Oreo-Mcflurry** [comment]
할 수 있...을껄요?
