### ISSUE TITLE
QA 수정

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#167]
## 🐛 Description
QA 수정하기
### Main
    - 날짜 패딩(영어 버전)
## 📝 TODO
- [x] latest perfomance → latest show워딩 수정
- [x] 스크롤 했을 때 서치바 밑에 패딩주기
- [x] V가 해외 아티스트로 나옴
- [x] 다크모드시 “찜한 아티스트 중 상단의 5명이~” 부분 색깔 적용 안 됨
