### ISSUE TITLE
Info.plist Localization

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#169]
## 🛠 Issue
- 사진/애플뮤직 접근 권한 설명을 현지화합니다
- 메일 양식을 현지화합니다
- 이참에 perfomance -> show 수정

## 📝 To-do
- [x] 사진 접근권한 현지화
- [x] 영어 접근권한 현지화
- [x] 메일 양식 현지화
- [x] perfomance -> show 수정
