### ISSUE TITLE
QA 수정 2

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#172]
## 🐛 Description
- 노엘겔러거 예외처리
- 아티스트뷰모델 북마크 토글해주는 변수 State로 빼기
- 다크모드 티켓 색깔
- 메인뷰 전체적인... 얼라인 수정

## 📝 TODO
- [x] 노엘겔러거 예외처리
- [x] 아티스트뷰모델 북마크 토글해주는 변수 State로 빼기
- [x] 다크모드 티켓 색깔
- [x] 메인뷰 전체적인... 얼라인 수정
