### ISSUE TITLE
메인뷰 아티스트 불러오는 방법 변경

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#178]
## 🐛 Description
**메인 뷰에서 아티스트 세트리스트를 불러올 때** **한 번에 너무 많은 정보를 불러와 세트리스트가 있음에도 불구하고 못 가져오는 문제**가 발생합니다.

## 📝 TODO
- [ ] 메인뷰 아티스트 불러오는 방법 고치기... (메인 뷰에 뜨는 아티스트 순서대로 순차적으로 불러오기)
- [ ] 메인뷰 디자인 조금 수정(패딩값)
- [ ] 내비게이션 타이틀에 나머지 콘텐츠 정렬 맞추기
- [ ] 국내 아티스트 위치 = 세트리스트 추가 및 수정하기
