### ISSUE TITLE
SettingView UI 수정

### ISSUE THREAD

**Issue by suri0000** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#202]
## 🛠 Issue
- SettingView UI를 수정합니다.

## 📝 To-do
- [x] Setlist.fm 바로가기 버튼 수정
- [x] 전체적인 패딩 줄이기
- [x] 문의하기 메일 취소 버튼 색 변경
