### ISSUE TITLE
아티스트뷰 수정

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#218]
## 🛠 Issue
- 아티스트뷰 수정

## 📝 To-do
- [x] 북마크 한 공연 여러 개일 때 슬라이드 기능 구현
<img src="https://github.com/user-attachments/assets/1e438071-e01c-44b8-8d8b-1094ec7f11b8" width=300>

- [ ] 공연 이름 없을 때 표기 방식 변경
<img src="https://github.com/user-attachments/assets/38c9d428-69ef-48a8-9568-6ccc205f1c57" width=300>

- [x] 하트 버튼 애니메이션
- [x] 아티스트 사진 없을 때 이미지 수정 (티켓 -> 사람)
- [x] 세트리스트 없을 때 뷰
