### ISSUE TITLE
MainView QA 적용 및 애플뮤직 속도 개선

### ISSUE THREAD

**Issue by wonniiii** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#235]
## 🛠 Issue
- 메인뷰의 전반적인 UI를 변경합니다.
- 애플뮤직 속도 개선 및 UI를 생성합니다.

## 📝 To-do
- [x] 메인뷰 artistImageView 탭바로 변경
- [x] align, padding 피그마 참고해서 맞추기
- [x] 메인뷰 UI 변경
- [x] 애플뮤직 속도 개선
