### ISSUE TITLE
MainView UI 구현

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#3]
## 🛠 Issue
- MainView UI 구현하기
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/364c102f-6854-43b8-8304-89953e9996d1)

## 📝 To-do
- [ ] 상단 배너 스크롤(무한 스크롤+자동 스크롤) 구현
- [x] 내가 찜한 공연 구현
- [x] 다가오는 공연 구현
- [x] 인기 아티스트 구현
