### ISSUE TITLE
Artist View 사소한 수정사항들

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#45]
## 🐛 Description
1. Woodz를 선택했는데 Miky Woodz 사진이 들어감
2. Artist Image 비율 안맞음
3. Artist View에서 Setlist View 호출 필요

## 📝 TODO
- [ ] 1. Genius 검색 로직 수정
- [ ] 2. 이미지 크롭으로 변경
- [ ] 3. NavigationLink destination 설정
