### ISSUE TITLE
MainView 수정

### ISSUE THREAD

**Issue by sumintnals** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#76]
## 🛠 Issue
- 메인 뷰 수정하기
![image](https://github.com/DeveloperAcademy-POSTECH/MacC-Team12-Creative8/assets/127755029/5fc9ebf9-222f-4024-bbef-a99e050714c5)

## 📝 To-do
- [x] 최근 좋아요 한 아티스트가 첫 화면으로 나오게 -> **일단 이건 아카이브 뷰에서 아티스트 순서 변경할 수 있게 하는 거 생각해서 제일 마지막에 건들겠습니다**
- [x] 아티스트 이미지 & 공연 리스트 사이 텍스트 추가
- [x] 세트리스트 있을 시 -세트리스트의 가장 첫곡을 보여주기/없을 시 -’세트리스트 정보가 아직 없습니다’ 보여주기
- [x] 로고&다크모드 버튼 -> 툴바로 수정
- [x] 색상 수정
- [ ] 내비게이션 링크 추가
