### ISSUE TITLE
OnboardingView 구현 완성

### ISSUE THREAD

**Issue by wonniiii** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#79]
## 🛠 Issue
- OnboardingView ver 1.0 완성

## 📝 To-do 
- [ ] 엑셀 데이터 불러오기
- [ ] 필터 기능 적용
- [ ] 토스트 만들기
- [ ] 아티스트 선택 액션 적용
