### ISSUE TITLE
ArtistView 수정

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#81]
## 🛠 Issue
- ArtistView 수정

## 📝 To-do
- [x] UI 변경사항 반영
- [x] SongList 자료형 변경(Tuple -> Struct)
- [x] Genius에서 아티스트 찾지 못했을 때 디폴트 이미지 적용
- [x] 비어있는 세트리스트 표시
