### ISSUE TITLE
Some bugs in the Artist view and Setlist view

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#95]
## 🐛 Description
머지하고 발견한 몇 기지 버그 수정

## 📝 TODO
- [x] 북마크된 세트리스트 조회 시 데이터가 제대로 전달되지 않는 문제
- [x] Genius에서 아티스트를 찾지 못했을 때 들어갈 디폴트 이미지 추가
- [x] 아카이빙 뷰에서 좋아요한 아티스틑 순서 바꿨을 때 메인뷰에 적용되지 않음
