### ISSUE TITLE
Apply SetlistView design changes

### ISSUE THREAD

**Issue by Ko-HyeJi** [DeveloperAcademy-POSTECH/MacC-Team12-Creative8#97]
## 🛠 Issue
- 세트리스트 뷰 디자인 변경사항 적용

## 📝 To-do
- [x] 세트리스트 캡처하기 토스트팝업
- [x] '플레이리스트 내보내기' 버튼 눌렀을 때 버튼 글자색 변경
- [x] 하단 영역 패딩 값 조절
- [x] 'setlist.fm 바로가기' 버튼 색 변경
- [x] 북마크 토스트팝업 위치 수정
